#where docqueues are

#persisted document queue
docqueue.features.tmpdir= ${ht_home}/tmpqueue/features
docqueue.features.queuedir= file://${ht_home}/queue/features
docqueue.features.partitioner.class = ht.features.FeatureDatePartitioner

#persisted feature queue
docqueue.docs.tmpdir= ${ht_home}/tmpqueue/docs
docqueue.docs.queuedir= file://${ht_home}/queue/docs

