###############
### EJB 3.0 ###
###############

## select Hibernate persistence provider

javax.persistence.provider=org.hibernate.ejb.HibernatePersistence
javax.persistence.transactionType=RESOURCE_LOCAL
javax.persistence.validation.factory=org.hibernate.validator.HibernateValidator
#javax.persistence.validation.factory=org.hibernate.validator.engine.ConstraintValidatorFactoryImpl
## entity bean class name (comma separated)


#hibernate.ejb.classes org.hibernate.ejb.test.Item, org.hibernate.ejb.test.Distributor

## entity caching (strategy, optional region name)
#hibernate.ejb.classcache.org.hibernate.ejb.test.Item read-write, RegionName
#hibernate.ejb.classcache.org.hibernate.ejb.test.Item read-write

## collection caching (role, optional region name)
#hibernate.ejb.collectioncache.org.hibernate.ejb.test.Item.distributors read-write, RegionName

######################
### Query Language ###
######################

## define query language constants / function names

dbconfig.hibernate.query.substitutions=true 1, false 0, yes 'Y', no 'N'

dbconfig.hibernate.bytecode.provider=javassist

## select the classic query parser

#hibernate.query.factory_class org.hibernate.hql.classic.ClassicQueryTranslatorFactory



#################
### Platforms ###
#################

## JNDI Datasource

#hibernate.connection.datasource jdbc/test
#hibernate.connection.username db2
#hibernate.connection.password db2

## MySQL

#dbconfig.hibernate.dialect=org.hibernate.dialect.MySQLDialect
dbconfig.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

#hibernate.dialect org.hibernate.dialect.MySQLMyISAMDialect
#dbconfig.hibernate.connection.driver_class=org.gjt.mm.mysql.Driver
dbconfig.hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
#hibernate.connection.driver_class=com.mysql.jdbc.Driver
dbconfig.hibernate.connection.url=jdbc:mysql:///test
dbconfig.hibernate.connection.username=<username>
dbconfig.hibernate.connection.password=<password>



#################################
### Hibernate Connection Pool ###
#################################

dbconfig.hibernate.connection.pool_size=80

###########################
### C3P0 Connection Pool###
###########################

dbconfig.hibernate.c3p0.max_size=80
dbconfig.hibernate.c3p0.min_size=4
dbconfig.hibernate.c3p0.initialSize=4
dbconfig.hibernate.c3p0.timeout=600
#dbconfig.hibernate.c3p0.max_statements 100
dbconfig.hibernate.c3p0.idle_test_period=300
dbconfig.hibernate.c3p0.acquire_increment=2
dbconfig.hibernate.c3p0.validate=false




##############################
### Proxool Connection Pool###
##############################

## Properties for external configuration of Proxool

dbconfig.hibernate.proxool.pool_alias=pool1

## Only need one of the following

#hibernate.proxool.existing_pool true
#hibernate.proxool.xml proxool.xml
#hibernate.proxool.properties proxool.properties



#################################
### Plugin ConnectionProvider ###
#################################

## use a custom ConnectionProvider (if not set, Hibernate will choose a built-in ConnectionProvider using hueristics)

#dbconfig.hibernate.connection.provider_class org.hibernate.connection.DriverManagerConnectionProvider
#dbconfig.hibernate.connection.provider_class org.hibernate.connection.DatasourceConnectionProvider
#dbconfig.hibernate.connection.provider_class org.hibernate.connection.C3P0ConnectionProvider
#dbconfig.hibernate.connection.provider_class org.hibernate.connection.DBCPConnectionProvider
#dbconfig.hibernate.connection.provider_class org.hibernate.connection.ProxoolConnectionProvider



#######################
### Transaction API ###
#######################

## Enable automatic flush during the JTA beforeCompletion() callback
## (This setting is relevant with or without the Transaction API)

#hibernate.transaction.flush_before_completion


## Enable automatic session close at the end of transaction
## (This setting is relevant with or without the Transaction API)

#hibernate.transaction.auto_close_session


## the Transaction API abstracts application code from the underlying JTA or JDBC transactions

#hibernate.transaction.factory_class org.hibernate.transaction.JTATransactionFactory
#hibernate.transaction.factory_class org.hibernate.transaction.JDBCTransactionFactory


## to use JTATransactionFactory, Hibernate must be able to locate the UserTransaction in JNDI
## default is java:comp/UserTransaction
## you do NOT need this setting if you specify hibernate.transaction.manager_lookup_class

#jta.UserTransaction jta/usertransaction
#jta.UserTransaction javax.transaction.UserTransaction
#jta.UserTransaction UserTransaction


## to use the second-level cache with JTA, Hibernate must be able to obtain the JTA TransactionManager

#hibernate.transaction.manager_lookup_class org.hibernate.transaction.JBossTransactionManagerLookup
#hibernate.transaction.manager_lookup_class org.hibernate.transaction.WeblogicTransactionManagerLookup
#hibernate.transaction.manager_lookup_class org.hibernate.transaction.WebSphereTransactionManagerLookup
#hibernate.transaction.manager_lookup_class org.hibernate.transaction.OrionTransactionManagerLookup
#hibernate.transaction.manager_lookup_class org.hibernate.transaction.ResinTransactionManagerLookup



##############################
### Miscellaneous Settings ###
##############################

## print all generated SQL to the console

#hibernate.show_sql true


## add comments to the generated SQL

#hibernate.use_sql_comments true


## generate statistics

#hibernate.generate_statistics true


## auto schema export

# DISABLED: Using JPA schema-generation instead to avoid repeated drops
#dbconfig.hibernate.hbm2ddl.auto=create
#hibernate.hbm2ddl.auto create
#hibernate.hbm2ddl.auto update


## specify a default schema and catalog for unqualified tablenames

#hibernate.default_schema test
#hibernate.default_catalog test
#dbconfig.hibernate.connection.characterEncoding=utf8
#dbconfig.hibernate.connection.useUnicode=true
#dbconfig.hibernate.use_sql_comments=true
#dbconfig.hibernate.show_sql=true
## enable ordering of SQL UPDATEs by primary key

dbconfig.hibernate.order_updates=true


## set the maximum depth of the outer join fetch tree

dbconfig.hibernate.max_fetch_depth=1


## set the default batch size for batch fetching

dbconfig.hibernate.default_batch_fetch_size=8


## rollback generated identifier values of deleted entities to default values

#hibernate.use_identifer_rollback true


## enable CGLIB reflection optimizer (enabled by default)

#hibernate.cglib.use_reflection_optimizer true



#####################
### JDBC Settings ###
#####################

## specify a JDBC isolation level

#hibernate.connection.isolation 4


## enable JDBC autocommit (not recommended!)

#hibernate.connection.autocommit true


## set the JDBC fetch size

#hibernate.jdbc.fetch_size 25


## set the maximum JDBC 2 batch size (a nonzero value enables batching)

#hibernate.jdbc.batch_size 5


## enable batch updates even for versioned data

dbconfig.hibernate.jdbc.batch_versioned_data=true


## enable use of JDBC 2 scrollable ResultSets (specifying a Dialect will cause Hibernate to use a sensible default)

#hibernate.jdbc.use_scrollable_resultset true


## use streams when writing binary types to / from JDBC

dbconfig.hibernate.jdbc.use_streams_for_binary=true


## use JDBC 3 PreparedStatement.getGeneratedKeys() to get the identifier of an inserted row

#hibernate.jdbc.use_get_generated_keys false


## choose a custom JDBC batcher

# hibernate.jdbc.factory_class


## enable JDBC result set column alias caching 
## (minor performance enhancement for broken JDBC drivers)

# hibernate.jdbc.wrap_result_sets


## choose a custom SQL exception converter

#hibernate.jdbc.sql_exception_converter



##########################
### LongSecond-level Cache ###
##########################

## optimize chache for minimal "puts" instead of minimal "gets" (good for clustered cache)

#hibernate.cache.use_minimal_puts true


## set a prefix for cache region names

#hibernate.cache.region_prefix hibernate.test


## disable the second-level cache

#hibernate.cache.use_second_level_cache false


## enable the query cache

#hibernate.cache.use_query_cache true


## store the second-level cache entries in a more human-friendly format

#hibernate.cache.use_structured_entries true


## choose a cache implementation

#dbconfig.hibernate.cache.provider_class org.hibernate.cache.EhCacheProvider
#hdbconfig.ibernate.cache.provider_class org.hibernate.cache.EmptyCacheProvider
#dbconfig.hibernate.cache.provider_class=org.hibernate.cache.HashtableCacheProvider
#dbconfig.hibernate.cache.provider_class org.hibernate.cache.TreeCacheProvider
#dbconfig.hibernate.cache.provider_class org.hibernate.cache.OSCacheProvider
#dbconfig.hibernate.cache.provider_class org.hibernate.cache.SwarmCacheProvider


## choose a custom query cache implementation

#hibernate.cache.query_cache_factory



############
### JNDI ###
############

## specify a JNDI name for the SessionFactory

#hibernate.session_factory_name hibernate/session_factory


## Hibernate uses JNDI to bind a name to a SessionFactory and to look up the JTA UserTransaction;
## if hibernate.jndi.* are not specified, Hibernate will use the default InitialContext() which
## is the best approach in an application server

#file system
#hibernate.jndi.class com.sun.jndi.fscontext.RefFSContextFactory
#hibernate.jndi.url file:/

#WebSphere
#hibernate.jndi.class com.ibm.websphere.naming.WsnInitialContextFactory
#hibernate.jndi.url iiop://localhost:900/




#dbconfig.hibernate.dialect=org.hibernate.dialect.MySQLDialect
dbconfigderby.hibernate.dialect=org.hibernate.dialect.DerbyDialect

#hibernate.dialect org.hibernate.dialect.MySQLMyISAMDialect
#dbconfig.hibernate.connection.driver_class=org.gjt.mm.mysql.Driver
dbconfigderby.hibernate.connection.driver_class=org.apache.derby.jdbc.EmbeddedDriver
#hibernate.connection.driver_class=com.mysql.jdbc.Driver
dbconfigderby.hibernate.connection.url=jdbc:derby:<dbname>;create=true
dbconfigderby.hibernate.connection.username=<username>
dbconfigderby.hibernate.connection.password=<password>


### derby setting ###
dbconfigderby.hibernate.use_sql_comments=false
