### main scheduler properties
scheduler.org.quartz.scheduler.instanceName = QuartzScheduler
scheduler.org.quartz.scheduler.instanceId = AUTO

### thread pool
scheduler.org.quartz.threadPool.threadCount = 7
scheduler.org.quartz.threadPool.threadPriority = 5
#scheduler.org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
scheduler.org.quartz.threadPool.class=com.hitorro.util.core.thread.QuartzCompatibleThreadPool
### for now, use an in-memory JobStore
scheduler.org.quartz.jobstore.class = org.quartz.simpl.RAMJobStore


